version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_SOCKET_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_PATH=/app/data/app.db
      - CORS_ORIGIN=http://localhost:5173
      - SOCKET_CORS_ORIGIN=http://localhost:5173
    env_file:
      - .env
    networks:
      - app-network

volumes:
  node_modules_frontend:
  node_modules_backend:
  sqlite_data:

networks:
  app-network:
    driver: bridge